config/routes.rb
Rails.application.routes.draw do

  root to: 'bicycles#index'
  resources :bicycles#, only: [:index]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bicycle.rb
class Bicycle < ApplicationRecord

  belongs_to :style
  belongs_to :brand

  validates :brand, presence: true
  validates :style, presence: true
  validates :model, presence: true
  validates :speeds, numericality: {only_integer: true, greater_than_or_equal_to: 1}

  # Optimization trick to have all brands and styles
  # available without N+1 queries
  default_scope { includes(:brand, :style) }


  def description
    "#{colour} #{formatted_speeds} #{brand.name} #{model} #{style.name}".gsub('  ', ' ')
  end


  def formatted_speeds
    return '' if speeds == 1
    "#{speeds}-speed"
  end

end

# create_table "bicycles", force: :cascade do |t|
#   t.string   "model"
#   t.string   "colour"
#   t.integer  "speeds"
#   t.integer  "style_id"
#   t.integer  "brand_id"
#   t.datetime "created_at", null: false
#   t.datetime "updated_at", null: false
#   t.index ["brand_id"], name: "index_bicycles_on_brand_id"
#   t.index ["style_id"], name: "index_bicycles_on_style_id"
# end

app/models/brand.rb
class Brand < ApplicationRecord

  has_many :bicycles

  validates :name, presence: true
  validates :country, presence: true

end

app/models/style.rb
class Style < ApplicationRecord

  has_many :bicycles

  validates :name, presence: true
end

# create_table "styles", force: :cascade do |t|
#   t.string   "name"
#   t.datetime "created_at", null: false
#   t.datetime "updated_at", null: false
# end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/bicycles_controller.rb
class BicyclesController < ApplicationController

  def index
    @bicycles = Bicycle.all
    @bicycles = @bicycles.where(model: params[:model]) unless params[:model].blank?
    @bicycles = @bicycles.where(style: params[:style]) unless params[:style].blank?
    @bicycles = @bicycles.where(brand: params[:brand]) unless params[:brand].blank?
    @bicycles = @bicycles.where(speeds: params[:speeds]) unless params[:speeds].blank?
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bicycles/index.html.erb
<h1>All My Bicycles!</h1>

<div class="search-form">
  <%= form_tag(bicycles_path, method: :get) do %>
    <div class="form-component">
      <%= label_tag(:model, 'Model ') %>
      <%= text_field_tag(:model, nil, size: 30) %>
    </div>

    <div class="form-component">
      <%= label_tag(:style, 'Style ') %>
      <%= select_tag(:style, options_from_collection_for_select(Style.all, :id, :name), include_blank: true) %>
    </div>

    <div class="form-component">
      <%= label_tag(:brand, 'Brand ') %>
      <%= select_tag(:brand, options_from_collection_for_select(Brand.all, :id, :name), include_blank: true) %>
    </div>

    <div class="form-component">
      <%= label_tag(:speeds, 'Speeds ') %>
      <%= number_field_tag(:speeds, nil, min: 1, max: 21) %>
    </div>

    <div class="form-component">
      <%= submit_tag('Search!') %>
    </div>
  <% end %>
</div>

<section class="bicycle-list" id="bicycle-list">
  <% @bicycles.each do |bicycle| %>
    <div class="bicycle">
      <h3 class="description"><%= bicycle.description %></h3>
      <p class="details">
        <strong>Country:</strong> <%= bicycle.brand.country %> |
        <strong>Brand:</strong> <%= bicycle.brand.name %> |
        <strong>Model:</strong> <%= bicycle.model %> |
        <strong>Style:</strong> <%= bicycle.style.name %> |
        <strong>Speeds:</strong> <%= bicycle.speeds %>
      </p>
    </div>
  <% end %>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Code</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>